version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: medusa-server-default
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./deploy.sh:/app/deploy.sh

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    expose:
      - 6379
  adminer:
    image: adminer
    restart: always
    ports:
     - "8081:8080"
volumes:
  pg-data: